gems: [jekyll-paginate, jekyll-sitemap,jekyll-admin]

# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Mengwei LIN
# Description of the Site
description: Welcome to my webpage!
# URL of Image of the Site
site-image: /assets/images/image.jpg
# Keywords of the Site
site-keywords:
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/background.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mengwei.lin@ub.edu
#facebook_username: /
#twitter_username:
#instagram_username: / 
linkedin_username: mengwei-lin-854488209
#github_username: /
#youtube_channel_id: /
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname:

# Name of the Author
author-name: Mengwei LIN
# URL for the Image of the Author
author-image: /assets/images/image.jpg
# 60 Words About the Author
author-about:       
                    <span>I am a PhD candidate at the Department of Economics,</span><span><a style ='color: inherit; text-decoration: underline;' href='https://www.ub.edu/school-economics/'>School of Economics at the University of Barcelona</a></span><span>and a predoctoral researcher at the</span><span><a style ='color: inherit;text-decoration:underline' href='https://www.ieb.ub.edu/en/'>Barcelona Institute of Economics (IEB).</a></span></p>
                    <br>
                    <p style="text-align: justify"><span>My research interests are in the </span><span><strong>Economics of Education, Labor Economics, Public Policy, and Causal Inference</strong></span>.</p>
                    <br>
                    <p style="text-align: justify"><span>Besides, I work as a certified English-Chinese translator, focusing on book translation in the general field of Social Sciences. (Latest:</span><span><a style ='color: inherit' href="http://opac.nlc.cn/F/?request=%E7%BB%8F%E6%B5%8E%E5%AD%A6%E6%80%8E%E4%B9%88%E4%BA%86&func=find-m&find_code=WRD&FIND_BASE=NLC01&FIND_BASE=NLC09" >《经济学怎么了》</a></span><span>- <i>What's Wrong with Economics?</i> by Robert Skidelsky) </span>
  # Hi! I am a PhD candidate at the Department of Economics of the University of Barcelona, and a predoctoral researcher at the Barcelona Institute of Economics (IEB). 
  #             My research interests are in the Economics of Education, Labor Economics, Public Policy, and Causal Inference.
  #             Besides, I also work as a certified English-Chinese translator, focusing on book translation in the general field of Social Sciences. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
#permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  # -
  #   scope:
  #     type: 'posts'
  #   values:
  #     layout: post
  #     post-image: ""
  #     description: ""
  #     tags:
  #       - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
