gems: [jekyll-paginate, jekyll-sitemap,jekyll-admin]

# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Mengwei LIN 林孟蔚

# Description of the Site
description: Welcome! <br><br> I am an applied micro and education economist.<br>
# URL of Image of the Site
site-image: /assets/images/image.jpg
# Keywords of the Site
site-keywords: 
  - Mengwei Lin;
  - 林孟蔚;
  - economics;
  - economics of education;
  - applied economics;
  - Barcelona;
  - 巴塞罗那大学;
  - education;
  - Mengwei;
  - 孟蔚;
# URL for the Image of custom Favicon
favicon-url: /assets/images/image.jpg

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/background.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mengwei.lin@ub.edu
#facebook_username: /
twitter_username: LIN_Mengwei
#instagram_username: / 
linkedin_username: lin-mengwei/?locale=en
bluesky_username: mengweilin
#github_username: /
#youtube_channel_id: /
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname:

# Name of the Author
author-name: Mengwei LIN
# URL for the Image of the Author
author-image: /assets/images/image.jpg
# 60 Words About the Author
author-about: Personal Webpage of Mengwei Lin (林孟蔚), PhD Candidate at Uni Barcelona & IEB, working on Econonics of Education. He is also a English-Chinese translator.
 # URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/lin-mengwei/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
#permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  # -
  #   scope:
  #     type: 'posts'
  #   values:
  #     layout: post
  #     post-image: ""
  #     description: ""
  #     tags:
  #       - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  courses:
    output: true
    permalink: /:title.html
